# Generated by Django 3.0.5 on 2020-05-17 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('title', models.CharField(max_length=100)),
                ('images', models.ImageField(null=True, upload_to='images//')),
                ('price', models.IntegerField()),
                ('catagory', models.CharField(choices=[('electronics', 'electronics'), ('clothing', 'clothing'), ('vehicle', 'vehicle')], default='electronics', max_length=50)),
            ],
        ),
    ]
